# ==========================================
# CONFIGURACIÓN DEL SERVIDOR LOCAL
# ==========================================
spring.application.name=CustomerService
server.port=8082

# ==========================================
# CONEXIÓN A SUPABASE (PostgreSQL)
# ==========================================
spring.datasource.url=jdbc:postgresql://db.zrdkgnmekannyahcwmbo.supabase.co:5432/postgres?user=postgres&password=Kantus_Microservicios&currentSchema=customer_db
spring.datasource.driver-class-name=org.postgresql.Driver

# Optimización del pool de conexiones para la nube
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1

# ==========================================
# CONFIGURACIÓN DE HIBERNATE / JPA
# ==========================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=customer_db

# 'update' creará las tablas automáticamente si no existen
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL en consola (ideal para ver si está funcionando)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
